name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r environment.txt

    - name: Run tests
      run: pytest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t 865864633/image-classification:latest .

# 8. 检查 Dockerfile 安全性
    - name: Scan Dockerfile
      run:
        sudo apt-get install -y trivy
        trivy config --severity HIGH,CRITICAL .

# 9. 推送 Docker 镜像
    - name: Push Docker image
      run: docker push 865864633/image-classification:latest